export const organisations = {
  featured: [
    { name: 'Financial Services (Banking Division)', href: '/V7/NewGrievance/Index/REVBQkQ%3d' },
    { name: 'Labour and Employment', href: '/V7/NewGrievance/Index/TU9MQlI%3d' },
    { name: 'Central Board of Direct Taxes (Income Tax)', href: '/V7/NewGrievance/Index/Q0JPRFQ%3d' },
    { name: 'Posts', href: '/V7/NewGrievance/Index/RFBPU1Q%3d' },
    { name: 'Telecommunications', href: '/V7/NewGrievance/Index/RE9URUw%3d' },
    { name: 'Home Affairs', href: '/V7/NewGrievance/Index/TUlOSEE%3d' },
    { name: 'Housing and Urban Affairs', href: '/V7/NewGrievance/Index/RE9VUkQ%3d' },
    { name: 'Personnel and Training', href: '/V7/NewGrievance/Index/RE9QQVQ%3d' },
    { name: 'Health & Family Welfare', href: '/V7/NewGrievance/Index/REhMVEg%3d' },
    { name: 'Financial Services (Insurance Division)', href: '/V7/NewGrievance/Index/REVBSUQ%3d' },
  ],
  more: [
    { name: 'Agriculture and Farmers Welfare', value: 'DOAAC' },
    { name: 'Agriculture Research and Education', value: 'DOARE' },
    { name: 'Animal Husbandry, Dairying', value: 'DOAHD' },
    { name: 'Atomic Energy', value: 'DATOM' },
    { name: 'Ayush', value: 'AYUSH' },
    { name: 'Bio Technology', value: 'DBIOT' },
    { name: 'Central Board of Excise and Customs', value: 'CBOEC' },
    { name: 'Chemicals and Petrochemicals', value: 'DOCPC' },
    { name: 'Civil Aviation', value: 'MOCAV' },
    { name: 'Coal', value: 'MCOAL' },
    { name: 'Commerce', value: 'DOCOM' },
    { name: 'Consumer Affairs', value: 'DOCAF' },
    { name: 'Cooperation', value: 'MOCOP' },
    { name: 'Corporate Affairs', value: 'DCOYA' },
    { name: 'Culture', value: 'DCLTR' },
    { name: 'Defence', value: 'MODEF' },
    { name: 'Defence Finance', value: 'FADSS' },
    { name: 'Defence Production', value: 'DDPRO' },
    { name: 'Defence Research and Development', value: 'DDRDO' },
    { name: 'Development of North Eastern Region', value: 'DONER' },
    { name: 'Drinking Water and Sanitation', value: 'DODWS' },
    { name: 'Earth Sciences', value: 'DOCND' },
    { name: 'Economic Affairs', value: 'DOEAF' },
    { name: 'Electronics & Information Technology', value: 'MINIT' },
    { name: 'Empowerment of Persons with Disabilities', value: 'DODAF' },
    { name: 'Environment, Forest and Climate Change', value: 'MOEAF' },
    { name: 'Ex Servicemen Welfare', value: 'DDESW' },
    { name: 'Expenditure', value: 'DOEXP' },
    { name: 'External Affairs', value: 'MEAPD' },
    { name: 'Fertilizers', value: 'DOFZR' },
    { name: 'Financial Services (Pension Reforms)', value: 'DEAPR' },
    { name: 'Fisheries', value: 'DFSHR' },
    { name: 'Food and Public Distribution', value: 'DOFPD' },
    { name: 'Food Processing Industries', value: 'DOFPI' },
    { name: 'Health Research', value: 'DHRES' },
    { name: 'Heavy Industry', value: 'DHIND' },
    { name: 'Higher Education', value: 'DSEHE' },
    { name: 'Information and Broadcasting', value: 'MOIAB' },
    { name: 'Investment & Public Asset Management', value: 'DODIV' },
    { name: 'Justice', value: 'DEPOJ' },
    { name: 'Land Resources', value: 'DOLDR' },
    { name: 'Legal Affairs', value: 'DLGLA' },
    { name: 'Legislative Department', value: 'LGVED' },
    { name: 'Micro Small and Medium Enterprises', value: 'MMSME' },
    { name: 'Military Affairs', value: 'DMAFF' },
    { name: 'Mines', value: 'MMINE' },
    { name: 'Minority Affairs', value: 'MOMAF' },
    { name: 'New and Renewable Energy', value: 'MONRE' },
    { name: 'NITI Aayog', value: 'DPLNG' },
    { name: 'O/o the Comptroller & Auditor General of India', value: 'CAGAO' },
    { name: 'Official Language', value: 'JSOLD' },
    { name: 'Panchayati Raj', value: 'MOPRJ' },
    { name: 'Parliamentary Affairs', value: 'MINPA' },
    { name: 'Petroleum and Natural Gas', value: 'MPANG' },
    { name: 'Pharmaceutical', value: 'DPHAM' },
    { name: 'Power', value: 'MPOWR' },
    { name: 'Promotion of Industry and Internal Trade', value: 'DOIPP' },
    { name: 'Public Enterprises', value: 'DPUBE' },
    { name: 'Railways, ( Railway Board)', value: 'MORLY' },
    { name: 'Revenue', value: 'DORVU' },
    { name: 'Road Transport and Highways', value: 'MORTH' },
    { name: 'Rural Development', value: 'DORLD' },
    { name: 'School Education and Literacy', value: 'DOSEL' },
    { name: 'Science and Technology', value: 'DOSAT' },
    { name: 'Scientific & Industrial Research', value: 'DOSIR' },
    { name: 'Shipping', value: 'MSHPG' },
    { name: 'Skill Development and Entrepreneurship', value: 'DOSKD' },
    { name: 'Social Justice and Empowerment', value: 'MOSJE' },
    { name: 'Space', value: 'DSPAC' },
    { name: 'Sports', value: 'DSPRT' },
    { name: 'Staff Selection Commission', value: 'STAFF' },
    { name: 'Statistics and Programme Implementation', value: 'MOSPI' },
    { name: 'Steel', value: 'MOSTL' },
    { name: 'Textiles', value: 'MTXTL' },
    { name: 'Tourism', value: 'DTOUR' },
    { name: 'Tribal Affairs', value: 'MTRBL' },
    { name: 'Unique Identification Authority of India', value: 'UIDAI' },
    { name: 'Water Resources, River Development & Ganga Rejuvenuation,', value: 'MINWR' },
    { name: 'Women and Child Development', value: 'DOWCD' },
    { name: 'Youth Affairs', value: 'MOYAS' },
    { name: 'State Governments/Others', value: 'OTHER' },
  ],
} as const
