/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedContinuationRouteImport } from './routes/_authenticated/continuation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as PublicGrievancesIndexRouteImport } from './routes/public-grievances/index'
import { Route as PublicGrievancesPublicIdRouteImport } from './routes/public-grievances/$publicId'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAuthoritySlugRouteImport } from './routes/services.$authoritySlug'
import { Route as AuthenticatedGrievancesIndexRouteImport } from './routes/_authenticated/grievances/index'
import { Route as AuthenticatedGrievancesRegistrationIdRouteImport } from './routes/_authenticated/grievances/$registrationId'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiRealtimeTokenRouteImport } from './routes/api/ai/realtime-token'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api/attachments/$attachmentId'
import { Route as ApiAttachmentsUploadRouteImport } from './routes/api/attachments/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ServicesAuthoritySlugIndexRouteImport } from './routes/services.$authoritySlug.index'
import { Route as ServicesAuthoritySlugFormFormIdRouteImport } from './routes/services.$authoritySlug.form.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContinuationRoute =
  AuthenticatedContinuationRouteImport.update({
    id: '/continuation',
    path: '/continuation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicGrievancesIndexRoute = PublicGrievancesIndexRouteImport.update({
  id: '/public-grievances/',
  path: '/public-grievances/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicGrievancesPublicIdRoute =
  PublicGrievancesPublicIdRouteImport.update({
    id: '/public-grievances/$publicId',
    path: '/public-grievances/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAuthoritySlugRoute = ServicesAuthoritySlugRouteImport.update({
  id: '/$authoritySlug',
  path: '/$authoritySlug',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedGrievancesIndexRoute =
  AuthenticatedGrievancesIndexRouteImport.update({
    id: '/grievances/',
    path: '/grievances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrievancesRegistrationIdRoute =
  AuthenticatedGrievancesRegistrationIdRouteImport.update({
    id: '/grievances/$registrationId',
    path: '/grievances/$registrationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRealtimeTokenRoute = ApiAiRealtimeTokenRouteImport.update({
  id: '/api/ai/realtime-token',
  path: '/api/ai/realtime-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/api/attachments/$attachmentId',
    path: '/api/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAttachmentsUploadRoute = ApiAttachmentsUploadRouteImport.update({
  id: '/api/attachments/upload',
  path: '/api/attachments/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAuthoritySlugIndexRoute =
  ServicesAuthoritySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServicesAuthoritySlugRoute,
  } as any)
const ServicesAuthoritySlugFormFormIdRoute =
  ServicesAuthoritySlugFormFormIdRouteImport.update({
    id: '/form/$formId',
    path: '/form/$formId',
    getParentRoute: () => ServicesAuthoritySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/continuation': typeof AuthenticatedContinuationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/public-grievances/$publicId': typeof PublicGrievancesPublicIdRoute
  '/services/$authoritySlug': typeof ServicesAuthoritySlugRouteWithChildren
  '/public-grievances/': typeof PublicGrievancesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/grievances/$registrationId': typeof AuthenticatedGrievancesRegistrationIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/realtime-token': typeof ApiAiRealtimeTokenRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/grievances/': typeof AuthenticatedGrievancesIndexRoute
  '/services/$authoritySlug/': typeof ServicesAuthoritySlugIndexRoute
  '/services/$authoritySlug/form/$formId': typeof ServicesAuthoritySlugFormFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/continuation': typeof AuthenticatedContinuationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/public-grievances/$publicId': typeof PublicGrievancesPublicIdRoute
  '/public-grievances': typeof PublicGrievancesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/grievances/$registrationId': typeof AuthenticatedGrievancesRegistrationIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/realtime-token': typeof ApiAiRealtimeTokenRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/grievances': typeof AuthenticatedGrievancesIndexRoute
  '/services/$authoritySlug': typeof ServicesAuthoritySlugIndexRoute
  '/services/$authoritySlug/form/$formId': typeof ServicesAuthoritySlugFormFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/continuation': typeof AuthenticatedContinuationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/public-grievances/$publicId': typeof PublicGrievancesPublicIdRoute
  '/services/$authoritySlug': typeof ServicesAuthoritySlugRouteWithChildren
  '/public-grievances/': typeof PublicGrievancesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/grievances/$registrationId': typeof AuthenticatedGrievancesRegistrationIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/realtime-token': typeof ApiAiRealtimeTokenRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/attachments/upload': typeof ApiAttachmentsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/grievances/': typeof AuthenticatedGrievancesIndexRoute
  '/services/$authoritySlug/': typeof ServicesAuthoritySlugIndexRoute
  '/services/$authoritySlug/form/$formId': typeof ServicesAuthoritySlugFormFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cookies'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/register'
    | '/services'
    | '/terms'
    | '/continuation'
    | '/dashboard'
    | '/drafts'
    | '/public-grievances/$publicId'
    | '/services/$authoritySlug'
    | '/public-grievances/'
    | '/services/'
    | '/grievances/$registrationId'
    | '/api/ai/chat'
    | '/api/ai/realtime-token'
    | '/api/attachments/$attachmentId'
    | '/api/attachments/upload'
    | '/api/auth/$'
    | '/grievances/'
    | '/services/$authoritySlug/'
    | '/services/$authoritySlug/form/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cookies'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/continuation'
    | '/dashboard'
    | '/drafts'
    | '/public-grievances/$publicId'
    | '/public-grievances'
    | '/services'
    | '/grievances/$registrationId'
    | '/api/ai/chat'
    | '/api/ai/realtime-token'
    | '/api/attachments/$attachmentId'
    | '/api/attachments/upload'
    | '/api/auth/$'
    | '/grievances'
    | '/services/$authoritySlug'
    | '/services/$authoritySlug/form/$formId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/cookies'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/register'
    | '/services'
    | '/terms'
    | '/_authenticated/continuation'
    | '/_authenticated/dashboard'
    | '/_authenticated/drafts'
    | '/public-grievances/$publicId'
    | '/services/$authoritySlug'
    | '/public-grievances/'
    | '/services/'
    | '/_authenticated/grievances/$registrationId'
    | '/api/ai/chat'
    | '/api/ai/realtime-token'
    | '/api/attachments/$attachmentId'
    | '/api/attachments/upload'
    | '/api/auth/$'
    | '/_authenticated/grievances/'
    | '/services/$authoritySlug/'
    | '/services/$authoritySlug/form/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CookiesRoute: typeof CookiesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  PublicGrievancesPublicIdRoute: typeof PublicGrievancesPublicIdRoute
  PublicGrievancesIndexRoute: typeof PublicGrievancesIndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiRealtimeTokenRoute: typeof ApiAiRealtimeTokenRoute
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
  ApiAttachmentsUploadRoute: typeof ApiAttachmentsUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/continuation': {
      id: '/_authenticated/continuation'
      path: '/continuation'
      fullPath: '/continuation'
      preLoaderRoute: typeof AuthenticatedContinuationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public-grievances/': {
      id: '/public-grievances/'
      path: '/public-grievances'
      fullPath: '/public-grievances/'
      preLoaderRoute: typeof PublicGrievancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-grievances/$publicId': {
      id: '/public-grievances/$publicId'
      path: '/public-grievances/$publicId'
      fullPath: '/public-grievances/$publicId'
      preLoaderRoute: typeof PublicGrievancesPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$authoritySlug': {
      id: '/services/$authoritySlug'
      path: '/$authoritySlug'
      fullPath: '/services/$authoritySlug'
      preLoaderRoute: typeof ServicesAuthoritySlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/grievances/': {
      id: '/_authenticated/grievances/'
      path: '/grievances'
      fullPath: '/grievances/'
      preLoaderRoute: typeof AuthenticatedGrievancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grievances/$registrationId': {
      id: '/_authenticated/grievances/$registrationId'
      path: '/grievances/$registrationId'
      fullPath: '/grievances/$registrationId'
      preLoaderRoute: typeof AuthenticatedGrievancesRegistrationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/realtime-token': {
      id: '/api/ai/realtime-token'
      path: '/api/ai/realtime-token'
      fullPath: '/api/ai/realtime-token'
      preLoaderRoute: typeof ApiAiRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/api/attachments/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/upload': {
      id: '/api/attachments/upload'
      path: '/api/attachments/upload'
      fullPath: '/api/attachments/upload'
      preLoaderRoute: typeof ApiAttachmentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$authoritySlug/': {
      id: '/services/$authoritySlug/'
      path: '/'
      fullPath: '/services/$authoritySlug/'
      preLoaderRoute: typeof ServicesAuthoritySlugIndexRouteImport
      parentRoute: typeof ServicesAuthoritySlugRoute
    }
    '/services/$authoritySlug/form/$formId': {
      id: '/services/$authoritySlug/form/$formId'
      path: '/form/$formId'
      fullPath: '/services/$authoritySlug/form/$formId'
      preLoaderRoute: typeof ServicesAuthoritySlugFormFormIdRouteImport
      parentRoute: typeof ServicesAuthoritySlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContinuationRoute: typeof AuthenticatedContinuationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedGrievancesRegistrationIdRoute: typeof AuthenticatedGrievancesRegistrationIdRoute
  AuthenticatedGrievancesIndexRoute: typeof AuthenticatedGrievancesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContinuationRoute: AuthenticatedContinuationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedGrievancesRegistrationIdRoute:
    AuthenticatedGrievancesRegistrationIdRoute,
  AuthenticatedGrievancesIndexRoute: AuthenticatedGrievancesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ServicesAuthoritySlugRouteChildren {
  ServicesAuthoritySlugIndexRoute: typeof ServicesAuthoritySlugIndexRoute
  ServicesAuthoritySlugFormFormIdRoute: typeof ServicesAuthoritySlugFormFormIdRoute
}

const ServicesAuthoritySlugRouteChildren: ServicesAuthoritySlugRouteChildren = {
  ServicesAuthoritySlugIndexRoute: ServicesAuthoritySlugIndexRoute,
  ServicesAuthoritySlugFormFormIdRoute: ServicesAuthoritySlugFormFormIdRoute,
}

const ServicesAuthoritySlugRouteWithChildren =
  ServicesAuthoritySlugRoute._addFileChildren(
    ServicesAuthoritySlugRouteChildren,
  )

interface ServicesRouteChildren {
  ServicesAuthoritySlugRoute: typeof ServicesAuthoritySlugRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAuthoritySlugRoute: ServicesAuthoritySlugRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CookiesRoute: CookiesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  PublicGrievancesPublicIdRoute: PublicGrievancesPublicIdRoute,
  PublicGrievancesIndexRoute: PublicGrievancesIndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiRealtimeTokenRoute: ApiAiRealtimeTokenRoute,
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
  ApiAttachmentsUploadRoute: ApiAttachmentsUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
